services:
  db:
    container_name: timescale_container
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: dev
    volumes:
      - ./timescaledb_data/data:/var/lib/postgresql/data
      - ./timescaledb_data/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql

